# Makefile.deps created Wed Dec  5 17:33:32 PST 2012
debugf.o: debugf.c debugf.h
hashset.o: hashset.c debugf.h hashset.h strhash.h
strhash.o: strhash.c strhash.h
spellchk.o: spellchk.c debugf.h hashset.h yyextern.h
